[tool.mypy]
mypy_path = "src"
explicit_package_bases = true
ignore_missing_imports = true
namespace_packages = true
strict = true

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
  "D",   # pydocstyle 
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort
  "B",   # flake8-bugbear
  "SIM", # flake8-simplify
  "UP",  # pyupgrade
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-bugbear]
# Allow default arguments like, e.g., `data: List[str] = fastapi.Query(None)`.
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]